Repository bazed-editor/bazed, pull requests merged in 2023-01, with the labels that each got.

#89 feat(vim): implement replace mode
  crates/bazed-core/src/buffer.rs
  crates/bazed-core/src/user_buffer_op.rs
  crates/bazed-core/src/vim_interface.rs
Labels: topic-vim

#97 feat(view): keep carets on screen when moving out of viewport
  crates/bazed-core/src/app.rs
  crates/bazed-core/src/buffer.rs
  crates/bazed-core/src/buffer/buffer_regions.rs
  crates/bazed-core/src/view.rs
Labels: topic-core

#101 Refactor (bazed-svelte): Use npm workspaces
  .github/workflows/ci.yaml
  .gitignore
  crates/bazed-tauri/build.rs
  crates/bazed-tauri/tauri.conf.json
  node_packages/bazed-svelte/.eslintignore
  node_packages/bazed-svelte/.eslintrc.cjs
  node_packages/bazed-svelte/.gitignore
  node_packages/bazed-svelte/.npmrc
  node_packages/bazed-svelte/.prettierignore
  node_packages/bazed-svelte/.prettierrc.yaml
  node_packages/bazed-svelte/README.md
  node_packages/bazed-svelte/package.json
  node_packages/bazed-svelte/playwright.config.ts
  node_packages/bazed-svelte/src/app.d.ts
  node_packages/bazed-svelte/src/app.html
  node_packages/bazed-svelte/src/index.test.ts
  node_packages/bazed-svelte/src/lib/Portion.svelte
  node_packages/bazed-svelte/src/lib/Rekuho.svelte
  node_packages/bazed-svelte/src/lib/Welcome.svelte
  node_packages/bazed-svelte/src/lib/common.ts
  node_packages/bazed-svelte/src/lib/config.ts
  node_packages/bazed-svelte/src/lib/core.ts
  node_packages/bazed-svelte/src/lib/event.ts
  node_packages/bazed-svelte/src/lib/font.ts
  node_packages/bazed-svelte/src/lib/linearAlgebra.ts
  node_packages/bazed-svelte/src/lib/rpc.ts
  node_packages/bazed-svelte/src/lib/theme.ts
  node_packages/bazed-svelte/src/lib/theme/kanagawa.ts
  node_packages/bazed-svelte/src/routes/+layout.ts
  node_packages/bazed-svelte/src/routes/+page.svelte
  node_packages/bazed-svelte/static/favicon.png
  node_packages/bazed-svelte/svelte.config.js
  node_packages/bazed-svelte/tests/test.ts
  node_packages/bazed-svelte/tsconfig.json
  node_packages/bazed-svelte/vite.config.js
  package-lock.json
  package.json
Labels: topic-ui, topic-frontend

#106 fix(movement): fix Motion::EndOfLine jumping into the next line
  crates/bazed-core/src/buffer/movement.rs
Labels: bug, topic-core

#114 chore: update dependencies
  Cargo.lock
  Cargo.toml
Labels: topic-chore

#113 ci: stop advisories from being an error
  .github/workflows/ci.yaml
Labels: topic-chore

#116 Add problem matcher
  .github/workflows/ci.yaml
Labels: topic-chore

#120 fix(bazed-svelte): fix autofocus textarea on startup
  node_packages/bazed-svelte/src/lib/Rekuho.svelte
Labels: bug, topic-frontend

#122 feat(bazed-svelte): Display selections in the frontend
  crates/bazed-core/src/app.rs
  crates/bazed-core/src/buffer.rs
  crates/bazed-core/src/document.rs
  crates/bazed-rpc/src/core_proto.rs
  node_packages/bazed-svelte/package.json
  node_packages/bazed-svelte/src/lib/Rekuho.svelte
  node_packages/bazed-svelte/src/lib/Welcome.svelte
  node_packages/bazed-svelte/src/lib/core.ts
  node_packages/bazed-svelte/src/lib/rpc.ts
  package-lock.json
Labels: enhancement, topic-frontend
